#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM microsoft/dotnet:2.2-sdk-alpine
COPY ["./src/Core", "/src/Core/"]
COPY ["./tests/Core/", "/tests/Core/"]
WORKDIR "/tests/Core"
ARG testCategory
ENV TEST_CATEGORY=$testCategory
CMD dotnet test --filter TestCategory=$TEST_CATEGORY --verbosity=minimal